<DOCTYPE html>                                                                                                                                                                                                                                 
<html>                                                                                                                                                                                                                                         
        <head>                                                                                                                                                                                                                                 
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8">                                                                                                                                                            
                <link rel="stylesheet" type="text/css" href="/css/style.css">                                                                                                                                                                   
                <title>About Daniel Jones</title>                                                                                                                                                                                              
        <body>                                                                                                                                                                                                                                 
                <div id="wrapper">                                                                                                                                                                                                             
                                                                                                                                                                                                                                               
                        <main>                                                                                                                                                                                                                 
                                <div id="content">                                                                                                                                                                                             
                                        <div class="innertube">                                                                                                                                                                               
<h1>BeamBot Panel</h1>
<iframe name="dummy" style="width:0;height:0;borider:0; border:none"> </iframe>
<form target="dummy" action="cgi-bin/server.py" method="post">
Send message: <input type="text" name="message">  <br />                                                              
<input type="submit" value="Submit" />                                                                                                                                                                                                         
</form>                                                                       </div>                                      
                                </div>                                                                                                                                                                                                         
                        </main>                                                                                                                                                                                                                
                                                                                                                                                                                                                                               
                        <?php $path = $_SERVER['DOCUMENT_ROOT'];                                                                                                                                                                                                             $path .= "/includes/navbar.php";                                                                                                                                                                                                               include("/var/www/includes/navbar.php"); ?>                                                                                                                                                                               
                                                                                                                                                                                                                                               
                </div>                                                                                                                                                                                                                         
        </body>                                                                                                                                                                                                                                
</html>    
